services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubuntu2204
    container_name: t_mongodb
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    env_file:
      - .env
  
  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    env_file:
      - .env

  postgres:
    image: postgres:17.6
    container_name: postgres
    restart: always
    shm_size: 128mb
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env

  adminer:
    image: adminer:5.4.1
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - cluster.name=${CLUSTER_NAME}
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data:z"
      - "./db/elasticsearch/jvm.options.d:/usr/share/elasticsearch/config/jvm.options.d:z"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=true
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - xpack.fleet.enabled=false
      - xpack.fleet.agents.enabled=false
      - xpack.fleet.packages.enabled=false
      - xpack.synthetics.enabled=false
    volumes:
      - "kibana_data:/usr/share/kibana/data:z"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  elasticsearch_data:
  kibana_data: